---
- name: Installing keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Installing keepalived
  ansible.builtin.dnf:
    name: keepalived
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Creating keepalived config
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Reload keepalived
