---
- name: Update all packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  become: true

- name: Installing haproxy
  ansible.builtin.apt:
    name: haproxy
    state: present
  become: true

- name: Creating haproxy config
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Reload haproxy
