---
- name: Installing haproxy
  ansible.builtin.apt:
    name:
      - haproxy
      - psmisc
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Installing haproxy
  ansible.builtin.dnf:
    name: haproxy
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Creating haproxy config
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Reload haproxy
